### ISSUE TITLE
Show error if host removed from queue while on manage page

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#117]
If a host is removed from a queue while they are sitting on the manage page for that queue, they see an error like:

![host removed manage error](https://user-images.githubusercontent.com/31591389/88559299-a7127600-cffa-11ea-84e7-54aff8b96aa7.png)

It would be better to show an error. My thinking is something like this, which is pretty generic and unhelpful, but I'm trying to think of all the ways someone could come upon a manage page link and not have access. Would love to hear @teshsopher 's thoughts too.

> **Access Denied.** You do not have access to this page. If you believe you are seeing this message in error, contact the queue host(s).

**Comment by teshsopher** [comment]
Another way that a person might get to the manage page and not have access is if someone (who was a host of the queue) shared the manage link with them and the person weren't a host.

@mfldavidson If the only case in which someone wouldn't have access to the manage page is if they weren't a host, we could say, "**Access Denied.** You are not a host of this queue. If you believe you are seeing this message in error, contact the queue(s) hosts." Otherwise, I think the message you've written is good, since it tells users what the error is (Access Denied), what happened (they don't have access/aren't a host), and what to do about it (contact the queue host(s)).

**Comment by mfldavidson** [comment]
Yeah I was thinking of that one too. That's a good suggestion for an error message. Let's go with that.

**Comment by teshsopher** [comment]
QA tested and working in dev on 8/14
