### ISSUE TITLE
Show error if queue deleted while host or attendee is on page

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#118]
Came up when testing #80 

If the queue is deleted while a host has the window open, that window refreshes to show a fully blank page with only the header nav and nothing else.

If the queue is deleted while an attendee has the window open and is in the line, that window refreshes to show the queue page as if the attendee is NOT in line, with an error at the top `Queue Connection: 1011`. Attempting to click "Join Queue" again results in error `Join Queue: Invalid pk "9" - object does not exist.`

Better UX for both IMO would be to show the `Queue Connection: The resource you're looking for could not be found. Maybe it was deleted?` error. @teshsopher can you weigh in?

**Comment by teshsopher** [comment]
@mfldavidson If the queue is deleted while a host or attendee is on a page related to it, I think it may be better to re-route them to an error page, so that they don't think there is still a queue to join/manage.

In terms of the text of the error, if we show one error for both the hosts and attendees, it may be better to say "Queue Connection Error: Queue no longer exists. It may have been deleted. Please contact the host(s) or the ITS Service Center if you need assistance." This lets everyone know what happened and gives an option for what to do next if they weren't expecting this error.

**Comment by mfldavidson** [comment]
I like that. I am not sure if this error is used elsewhere that makes this specificity problematic--I defer to the devs on that. But I think this should give enough guidance on a good-better-best style approach. Thanks Teshia!

**Comment by jlost** [comment]
This should be fixed, but I used the existing error text "Queue Connection: The queue was deleted." as that should be the only reason they would see the message.

**Comment by teshsopher** [comment]
QA tested and working in dev on 8/14
