### ISSUE TITLE
Agenda field

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#17]
It may be useful to provide a box to the students to enter a brief message that is only viewable by the teaching staff. We found it useful for students to indicate a brief reason for the office hours or to indicate where they are located.

This was noted as high priority by a beta tester.

**Comment by jlost** [comment]
This will involve: 
* Adding an Agenda text field to the Meeting model
* Adding (or ensuring already exists) the ability for an Attendee of a Meeting to change the Agenda of the Meeting through the REST API (non-Attendees shouldn't be able to change it)
* Adding an "Agenda" Single-Form Input to the Queue page which is only visible after the Attendee has joined the Queue, which sends to the above REST API upon submission
* Adding a "Agenda: xxxxx" text to the Join Info dialog box

**Comment by bruinc** [comment]
@teshsopher Hi Teshia, below are some screenshots of how the agenda field looks, any input you have would be highly appreciated!

When an attendee joins a queue, there is a new field prompting them to enter something for the agenda, but it's not required:
![field](https://user-images.githubusercontent.com/23128544/82087469-2bbd4b80-96be-11ea-9548-bde604a61efb.png)

After entering an agenda, it's shown and the attendee can also change it by clicking "Edit":
![field_entered](https://user-images.githubusercontent.com/23128544/82087532-498ab080-96be-11ea-9ed6-7b351be23fb3.png)

The host can see the agenda for a meeting by clicking the "Join Info" button for the meeting:
![meeting_list](https://user-images.githubusercontent.com/23128544/82087688-979fb400-96be-11ea-8a75-3b641f24c554.png)

Which opens up the corresponding dialog, and the agenda is there:
![join_info](https://user-images.githubusercontent.com/23128544/82087696-9cfcfe80-96be-11ea-854f-aba4b1762b4e.png)

**Comment by teshsopher** [comment]
For the attendee/visitor view:
It may be better to keep the width within one column, since there are two columns of content on this page. Also, the label of the field could say "Meeting Agenda (Optional)," to let users know right away that it's optional. Ideally, there would also be some help text underneath the label to say something like "Let the host(s) know the topic you wish to discuss," which would remove the need for placeholder text and would be much more accessible.

Everything else looks great!

A few questions two think about:
1. Should we limit the amount of text the attendee can put in this box? While I imagine most users aren't going to be writing paragraphs, it may be better for the host to make sure this is, at most, a sentence so it's easily scannable.
2. Should we bold the label so that it stands out a bit more?

**Comment by bruinc** [comment]
Here it is with those changes:
![feedback](https://user-images.githubusercontent.com/23128544/82091619-ae95d480-96c5-11ea-8085-74188e1570d5.png)

The character field required a maximum length, so I had made the arbitrary choice of a 100 character limit for the agenda field, but that can be changed to any other number.

**Comment by jlost** [comment]
Looks great, I merged it in. If we have any more tweaks to make to this, let's open them up as separate issues.

**Comment by bruinc** [comment]
This issue never got added to the project, but has been merged into 1.2 for some time, so sending it straight to QA.

**Comment by teshsopher** [comment]
Things I found while testing:

- There is no indicator or instruction text that the agenda needs to be less than 100 characters
- After typing in an agenda that is more than 100 characters, the Agenda field will act like an agenda has been added, displaying no text and just the edit button. It may be better for the field to remain as the text box and act as if text hasn't been entered yet/still being edited
![image](https://user-images.githubusercontent.com/63423382/88053791-644c2c00-cb2a-11ea-9d67-e8c9c02e9ada.png)
- If the attendee leaves the page and navigates back, the Agenda field displays the text box rather than the already set agenda and the "Edit" button. Is this the expected behavior, or should it display with the text and the edit button?

**Comment by bruinc** [comment]
I agree that it would be better for the error to show with the field still in the Edit state so that the user doesn't lose what they've written, and they can make the necessary modifications.

The reasoning behind making the agenda field be in the Edit state upon page load was to make it obvious and easy for the attendee to type something in as soon as they join the queue. But I agree, if they have already set the agenda, there is no need for it to be in the Edit state.

**Comment by teshsopher** [comment]
@bruinc I'm going to make this a new issue. Would this be better as two issues (i.e. "Keep Agenda in Edit State if There's an Error" and "Agenda in Edit State on Page load if no agenda") or is it better for you as one issue?

**Comment by bruinc** [comment]
@teshsopher One issue is good!
