### ISSUE TITLE
Back to Manage Queue button on settings page

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#208]
Users may have difficulty figuring out how to get back to the queue management page from the queue settings page because the only way to do it is by clicking in the breadcrumbs. Consider whether we need to add a "Back to Manage Queue" button--maybe down at the bottom by Save Changes? @teshsopher defer to you--we may need to test this

**Comment by ssciolla** [comment]
@mfldavidson, I thought about this at various times while working on these workflows. Pretty easy to implement, though I'm a little uncertain where exactly such a button should go.

**Comment by mfldavidson** [comment]
I think down next to Save Changes might make sense

**Comment by teshsopher** [comment]
I wonder if putting it near the top of the page might make more sense, since that's generally where navigation type links are located.

I have a rough mockup of both options to see (I hope I understand your suggestion, @mfldavidson, please correct me if I'm wrong!)

At the top of the page:
![Back to queue at top](https://user-images.githubusercontent.com/63423382/98129330-01876200-1e87-11eb-9343-3614fc8c2fb1.png)

Near the Save Changes button
![Back to queue near Save](https://user-images.githubusercontent.com/63423382/98129538-3c899580-1e87-11eb-942e-87393901e0c7.png)

**Comment by mfldavidson** [comment]
I like your top of page mockup. Let's do that.

**Comment by mfldavidson** [comment]
Since this is pretty quick and I'm finding in my testing that I think it's a bigger issue than I was originally thinking, let's try to get this in 1.3. @ssciolla can you do it?
