### ISSUE TITLE
Show character limit before typing starts

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#220]
The way we are doing validation, the character limit doesn't show until a user starts typing into the field. Can we show it all the time? So for example if the field has a 100 character limit, show "Remaining characters: 100/100" when first loading the page, not simply after typing starts.

**Comment by ssciolla** [comment]
I feel we've talked about this (or similar things) before, and I may have even had it working this way previously. I'd like to hear @teshsopher 's perspective. I think we chose our current approach because there are fields that are required (like the Queue name) that, if we validate immediately, will appear as invalid (red styling) without the user doing anything -- which doesn't seem great to me. With the current set up, they have to change something or hit enter before it starts to validate.

I'm willing to discuss this, but I've done a good amount of legwork to make the current approach work. And it makes sense to me that you wouldn't want to validate anything until you get an indication from the user that they want something to be saved or changed. Of course, you could separate this "Remaining characters" message from the other validation logic, but it really does feel like validation work to me.

**Comment by ssciolla** [comment]
I do understand why a user might want to know how many characters they can use before they type anything. I'm just a little frustrated because I agonized over this previously, and now it feels like we're doubling back.

**Comment by teshsopher** [comment]
I agree with Maggie that, in an ideal case, the count would be visible the whole time for the sake of clarity and error prevention. I do think that we have discussed this before, @ssciolla , so I understand your frustration. I think that, where the back and forth happened is when it came to validation, since, you're right, we are validating to see if this field is over/under the character limit.

I'm willing to leave it as is for now, but, ideally, it would be visible the whole time.

**Comment by mfldavidson** [comment]
I added this based on Zhen's feedback. If it isn't feasible or we have already discussed, we can close it as a won't fix. I have no opinion either way.
