### ISSUE TITLE
Feature: Bigger number to tell you your turn

### ISSUE THREAD

**Issue by jlost** [tl-its-umich-edu/remote-office-hours-queue#8]
I don't know what it looks like when there are people waiting, but I would like the number to be big and up front (like where the green part is for when it's your turn.

-- Eric Boyd

**Comment by jlost** [comment]
Hey @teshsopher, a mockup would be helpful for this. Or just your thoughts on the subject to get us started.

**Comment by teshsopher** [comment]
I have an [initial mockup](https://www.sketch.com/s/19df30a7-8d6c-4a17-9f30-5cbca9f63ec5/v/pYJ9vJ/) of a redesigned "Join Queue" experience based on some of the user feedback I've gotten, which includes emphasizing the attendee's place in line. These are just some of my initial thoughts/solutions, so I'm open to any changes/feedback that others may have!

**Comment by bruinc** [comment]
Following Teshia's mockup of the Join Queue page, here is a screenshot of what I have so far (working in the branch called attendee-turn-number):
![1](https://user-images.githubusercontent.com/23128544/82486126-6ce0a180-9aaa-11ea-8307-c365d0a014d7.png)

The card to right with more BlueJeans info doesn't show up when I run it locally because that container is only defined when the BlueJeans data is defined. I included another screenshot below of me just pasting in some HTML at runtime. Not a perfect representation of what it will look like, but roughly:
![1 mock](https://user-images.githubusercontent.com/23128544/82487490-681ced00-9aac-11ea-930f-e5f4b6c8eeaf.png)

Any thoughts/comments/suggestions are welcomed!

I also wanted to clarify something since I made an assumption. In the current app, it shows the number of people in front of the attendee, so it shows "0" when the attendee is next in line. Since Teshia's mockup shows "Your number in line" I added 1 to the line place currently shown, so it shows "1" when the attendee is next in line. Is that the correct interpretation?

**Comment by jlost** [comment]
Looks good, but the styling could use a bit of polish. It looks like there should be more of a margin underneath the new border, maybe less padding or less line-spacing(?), and the background color should be slightly different to draw your eye. I see bootstrap has a `highlight` class, maybe that would work?

**Comment by bruinc** [comment]
Update: I made the changes you mentioned @jlost, let me know if you had a different color in mind for the background of the card.
![v2](https://user-images.githubusercontent.com/23128544/84188447-9b2a1f00-aa61-11ea-9bfd-2354442b171c.png)

I also went back and looked at the mockup that @teshsopher made, and I noticed that she had next to the turn number a note that said when it was last updated in seconds. Should I try to implement that for this issue?

**Comment by jlost** [comment]
That looks perfect to me. As for the "last updated", does that mean last time their place in line changed, or the last time the client polled the server for their place in line? If the former, at least as a developer, I would consider "last changed" to be slightly clearer verbiage.

**Comment by teshsopher** [comment]
I intended the "Last Updated" to let users know when their place in line was last checked, so users are more aware of when this information has been updated. It may be better to say "Last Checked" instead, since the the user's place won't necessarily change every time it's polled.

As far as the duration of time, I used seconds since, right now, the refresh icon appears fairly often, but I'm open to however you want to display that!

**Comment by jlost** [comment]
Got it -- I have a half-finished PR open that will make the `/queue/id` and `/manage/id` pages realtime, removing the problem entirely, so we should just wait until that's ready to merge in.

**Comment by bruinc** [comment]
I started experimenting with a single-column layout that Teshia suggested as an option, and this is what I have now. I know the spacing at the bottom needs work and the turn-now alert language will need to be changed, but it at least shows the idea. Both the accordions and the "Join Meeting" button are all in the same BlueJeans-specific component.
![image](https://user-images.githubusercontent.com/23128544/86025730-8a375280-b9fc-11ea-8fea-f6a734293422.png)

And here are the accordions expanded:
![image](https://user-images.githubusercontent.com/23128544/86025812-ab983e80-b9fc-11ea-91af-45d08aa7caef.png)

And:
![image](https://user-images.githubusercontent.com/23128544/86025865-bce14b00-b9fc-11ea-9603-6010cff11b24.png)

@teshsopher @jlost Thoughts?
Also, I have not pushed this to the PR branch yet in case this isn't the direction we want to go in.

**Comment by jlost** [comment]
Spitballing some thoughts and ideas, in no particular order:
* Is the reason for the accordions to keep the "Join Meeting" from being pushed too far down on the page? If so, maybe it would be okay to leave them both "open" and put those two side-by-side in two columns.
* Expandable accordions should have some visual cue that they're expandable - I've typically right-aliged a carat on the right side of the headers whose up/down state denotes open/closed.
* What if the "Meeting Agenda" control were moved into the gray info box? It's a property (or "important piece of data") about your meeting after all, just like the other things in that box. I suggest this because "Meeting Agenda" where it is feels *off*. I think constraining its width would help somewhat as well.

**Comment by teshsopher** [comment]
> * Is the reason for the accordions to keep the "Join Meeting" from being pushed too far down on the page? If so, maybe it would be okay to leave them both "open" and put those two side-by-side in two columns.

My reason for the accordions was to reduce the (perceived) amount of content on the page. In the current design, the paragraphs are bulky, so I had pictured these below the "Join Meeting" button. However, seeing the instructions on a single-column layout, the text doesn't appear as compact, so it may be okay to skip the accordions. A side-by-side & expanded layout also works for me, if we want to keep the accordions!

> * What if the "Meeting Agenda" control were moved into the gray info box? It's a property (or "important piece of data") about your meeting after all, just like the other things in that box. I suggest this because "Meeting Agenda" where it is feels _off_. I think constraining its width would help somewhat as well.

I agree that this does feel off. We can try moving it into the gray box, but I would also suggest making the label a little bigger to bring it out a little more. I would also agree that reducing the width of the field would be helpful too.

**Comment by bruinc** [comment]
I'm still playing around with different things, but I wanted to add an update before the end of the day with what I have so far. 

- I put the agenda field in the gray box and reduced the width of the box in order to reduce the width of the agenda field. However, I think it will be best to either keep the gray box at full width and just reduce the width of the agenda field, or center the smaller gray box in the window.
- I moved the "Join Meeting" button above the help text so you don't have to scroll to the bottom for it.
- I made the two accordions into two side-by-side cards. I'm currently trying to force them to be the same height.
- How do you feel about the "Leave the line" link by itself at the bottom? The only other two options that allow for the meeting-specific things to be together in a single component are to 1) put the Join Meeting button back down to the bottom with it, 2) put the Leave the line link above the Join Meeting button. Any other configuration is possible if we pass the "OnLeaveQueue" prop to the BlueJeans meeting info component. 


![image](https://user-images.githubusercontent.com/23128544/86175747-e039f200-baf1-11ea-8a40-08b19b337e21.png)
![image](https://user-images.githubusercontent.com/23128544/86175795-f2b42b80-baf1-11ea-89ca-cd21d602d973.png)

**Comment by jlost** [comment]
Would it cause migration difficulties to push these changes to dev?

**Comment by bruinc** [comment]
@jlost I don't think that the migration files currently in dev will change at all if this branch is merged into it because the migration files in this branch are the older ones that have since been separated. However, I am not 100% confident because I'm still new to more intricate git histories.

**Comment by jlost** [comment]
No problem, you can try merging this to dev (force-pushing this branch to dev is also an option), and let me know if you run into any difficulties. I can wipe the dev database to reset any migration problems if need be.

**Comment by bruinc** [comment]
@jlost I merged this branch into dev with no migration issues. I can see that the code updated, but I do not see the changes on the dev website

**Comment by jlost** [comment]
Looks like the container service timed out when the webhook was sent from the push. I resent the payload an it worked. so it's building now and will deploy soon.

**Comment by bruinc** [comment]
Awesome, I can see the changes now

**Comment by jlost** [comment]
![image](https://user-images.githubusercontent.com/11338926/86358873-387e0a80-bc3e-11ea-9e35-b54866ac2960.png)
How does this look? I have some ideas about how to refactor the `BlueJeansMeetingInfo` to put extra actions buttons next to "Join Meeting" if this looks good.

**Comment by bruinc** [comment]
I think it looks great!

**Comment by jlost** [comment]
I was thinking we could allow arbitrary extra actions next to "Join Meeting" inside of the `BlueJeansMeetingInfo` instead of refactoring a "Leave line" action into the props, which I think doesn't really belong there conceptually (leaving the line has nothing to do with BlueJeans meetings, and the meeting and queue should ideally be separate concepts). 
If you take a look at `StatelessSingleInputForm` and `RemoveButton` you'll see a couple examples of this. `props.children` has the inner JSX elements. The `React.FC<T>` generic typing will add the `children` property to the props interface `T`.

**Comment by bruinc** [comment]
Merged- closing and moving to QA

**Comment by teshsopher** [comment]
Tested and Working in dev on 7/23
