### ISSUE TITLE
Use Django channels instead of polling at 3 second intervals

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#80]
To reduce server load and allow application to scale

**Comment by mfldavidson** [comment]
Testing (in progress)
One window on queue join page, another on manage queue page
- [x] Join queue, ensure appears in manage page = success
- [x] Leave queue, ensure disappears in manage page = success
- [x] Rename queue, ensure changes in join page = success
- [x] Change description, ensure changes in join page = success, EXCEPT doesn't change in popup, but if popup is closed and reopened, it shows changed, which technologically is expected but may not meet user expectations; I think it's fine, just pointing out
- [x] Delete meeting on host side, ensure changes to show no longer in line on join page = success

**Comment by mfldavidson** [comment]
I left it sitting on the queue page and came back to these 2 errors:
![image](https://user-images.githubusercontent.com/31591389/88557096-c956c480-cff7-11ea-944c-fa0873515987.png)

Good to tell people to refresh the page, but I wonder why 2 errors instead of 1 and not sure what "Refresh my user" means? I think this may be a question for @bruinc not sure

**Comment by jlost** [comment]
"Refresh My User" should be changed to say "User Connection". There are two separate errors because there are two separate websockets that this error could potentially originate from. Condensing them would be less confusing to users, but since they're already in Errorville I would prefer to prioritize getting more detail in the resultant bug report, and knowing which socket(s) disconnected is an important detail. 

How long did you leave the queue page before getting those errors? Did you do anything in-between, like change networks or disconnect?

**Comment by mfldavidson** [comment]
@jlost I can create a new issue for this. It was up on my computer, which fell asleep while I went for a 25 min walk. I didn't change networks but my computer did fall asleep so I assume it disconnected.

**Comment by jlost** [comment]
OK, I did test disconnecting the network for a few minutes which was handled surprisingly gracefully, but not going to sleep. That might be fairly common, so if it's reproducible we could think of a more user-friendly way to address it.

**Comment by mfldavidson** [comment]
I'm a pro at breaking things which is why I am accidentally decent at QA :)

**Comment by mfldavidson** [comment]
I think that so long as it says "refresh the page" that's the main thing that matters, so I'm going to call those errors fine for now. If we encounter confused users we can address then. But maybe I'm not speaking with my UX hat on straight.
