### ISSUE TITLE
Add Queue workflow

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#95]
Create a workflow for adding a new queue instead of the text entry on the Manage page. Refer to @teshsopher 's mockup for Add Queue Page https://www.sketch.com/s/88bccdc1-3ae0-4311-99a2-3dec82df2592

1. [Add Queue text entry field is replaced by an Add Queue button on the Manage page](https://www.sketch.com/s/88bccdc1-3ae0-4311-99a2-3dec82df2592/a/2vjp9J)

2. [Add Queue workflow page 1 has host enter Queue Name, Description (not required), and allowed meeting types](https://www.sketch.com/s/88bccdc1-3ae0-4311-99a2-3dec82df2592/a/Mj74kz)

3. [Add Queue workflow page 2 has host enter other hosts if applicable](https://www.sketch.com/s/88bccdc1-3ae0-4311-99a2-3dec82df2592/a/5GZKb8)

**Comment by ssciolla** [comment]
I'd wait to fully QA this until issue #94 is also closed, as there will be some shared code, meaning I'll be making changes that touch these components.

**Comment by teshsopher** [comment]
@ssciolla I did some testing with the Add Queue workflow. Everything seems to work as intended (errors throw as appropriate, queue is set up as expected, etc.). In terms of the accessibility of the Tab links that we discussed before, it may be possible to treat them as a sort of "sub-navigation." The current dev version looks like it handles the issue from before (where users couldn't click on the next section at all) well by allowing users to click on it and progress if they've filled out the fields as needed (and throwing the appropriate error if they haven't).

There are some other accessibility issues:
- The (Queue) Name field and the Description field in the General section and the "Add Host" field in the Manage Hosts section don't have labels (This is also related to issue #159 )
- There is contrast issues with the "Add Host" button (related to #155 ). Additionally, there is contrast issues with the "Cancel" button. I had intended this to be created like a link, so that it would be the "de-emphasized" action (so there aren't two buttons competing for attention, and to prevent errors, in case users mistake the "cancel" button to be the next action they should take), and the primary action ("Save") would be emphasized for users to know what to do next.

**Comment by ssciolla** [comment]
Thanks, @teshsopher. I am still mostly out sick at the moment, but I think I'll be back to working tomorrow. I think I've handled the missing labels with the Queue Settings PR I'm working on. I've also come up with a way there (maybe not the best way) to make the tab links keyboard accessible. I will try to get the PR updated and out to `dev` tomorrow. I will also look into the Cancel button issues you raised; I think I went with the button to help keep the styling consistent. What contrast ratios should I be paying attention to there? The button background, or the text?

**Comment by teshsopher** [comment]
@ssciolla Sounds good, take care of yourself! 

As far as the contrast ratios go, the button background should be what you're paying attention to, in the case of the Add Host button (since the button text color and general webpage background are the same).

**Comment by mfldavidson** [comment]
I tried really hard to break this and I could not, so as soon as the things Teshia is talking about are fixed (which it's up to you two if those should be new issues or not), this can move to Done. Thank you both!

**Comment by ssciolla** [comment]
> There are some other accessibility issues:
> 
>     * The (Queue) Name field and the Description field in the General section and the "Add Host" field in the Manage Hosts section don't have labels (This is also related to issue #159 )

I have a proposed solution to this in PR #185.

>     * There is contrast issues with the "Add Host" button (related to #155 ). Additionally, there is contrast issues with the "Cancel" button. I had intended this to be created like a link, so that it would be the "de-emphasized" action (so there aren't two buttons competing for attention, and to prevent errors, in case users mistake the "cancel" button to be the next action they should take), and the primary action ("Save") would be emphasized for users to know what to do next.

I think I addressed the Cancel button part of this in PR #173 by giving the buttons `link` styling. I'll tackle the rest of this in my work on #155.

**Comment by teshsopher** [comment]
Tested and working in QA
