### ISSUE TITLE
Self-service reporting by queue

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#97]
In order to meet the potential use case of lobby management, as well as to respond to general inevitable requests for reporting capabilities, Remote Office Hours Queue should make it possible for users to pull reports about usage of their queue. Some elements that may be important to report on include:

- Most popular times of the day, days of the week, and weeks of the year
- Number of attendees seen by each host
- Most popular words used in the agenda field
- Number of unique attendees in a period of time

Reporting could be implemented by sending Caliper events to the Unizin Data Platform (UDP) and providing reports that utilize the Google Cloud Platform connection to the UDP.

**Comment by mfldavidson** [comment]
Requested by 2 users to date.
- TDX 79708
- TDX 103155

**Comment by HemanginiShah** [comment]
[[TDX 5344805 - ](https://teamdynamix.umich.edu/TDNext/Apps/31/Tickets/TicketDet.aspx?TicketID=5344805)
advisors like to keep a record of who they talk to for follow ups. Currently they are manually recording the information and thought it would be easier if they could get a report from the queue itself

**Comment by hemashahumich** [comment]
Additional request for the historing data reporting feature: TDX:
https://teamdynamix.umich.edu/TDNext/Apps/31/Tickets/TicketDet.aspx?TicketID=5640567
https://teamdynamix.umich.edu/TDNext/Apps/31/Tickets/TicketDet.aspx?TicketID=5640293

Can we give this a high priority to include in next release?
Thanks.

**Comment by hemashahumich** [comment]
Another ticket came in with log request: https://teamdynamix.umich.edu/TDNext/Apps/31/Tickets/TicketDet.aspx?TicketID=5733961

**Comment by hemashahumich** [comment]
"1. Queue name is not appearing in downall all history button download csv file.  
2. Deleted queue are not getting listed. 
3. Can we get that to downloaded
Currently, the reporting button ""Download"" and the ""Download All Queue History"" are tracked based on the signed-in user.  Question: Should the admin or service manager have access to view the Download button or download all queue history button for a single queue and for all queues?"

**Comment by jonespm** [comment]
1. What do you mean by queue name, like in the report? Yes the query only has the queue id. I think including the name might take more effort since I'm not sure if it's in the log table and would need a join against the queue table. I feel adding this for this release could delay this a week. We could create an issue for next release. 
2. The admin or service manager doesn't have access to this currently only the hosts. This will have to be created as a new feature request for the admin page if desired. It's possible for dev for now to export the data directly using a GUI like DBeaver. I could create this issue. 

If you think these should be worked on in the future we can do it if we have time.
